# Frontend build settings
[build]
  base    = "frontend"
  publish = "frontend/dist"
  command = "npm run build"

# Backend function settings
[functions]
  directory = "../backend" # <-- THIS IS THE FIX

# Redirect rule to connect frontend to backend
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/:splat"
  status = 200