# This is the final and correct configuration for your project.

[build]
  # Command: This tells Netlify to first go into the frontend folder,
  # then install its specific dependencies, and finally run the build command.
  command = "cd frontend && npm install && npm run build"

  # Publish directory: The folder containing the built website files,
  # relative to the project's root.
  publish = "frontend/dist"

  # Functions directory: The folder containing your backend server code,
  # relative to the project's root.
  functions = "backend"

# Redirects: This rule connects your live frontend to your backend API.
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/:splat"
  status = 200