# This is the final and definitive configuration for your project.
# It handles the monorepo structure by running commands from the root.

[build]
  # This command does two things:
  # 1. `npm install`: Installs dependencies for BOTH frontend and backend from the root.
  # 2. `npm run build -w frontend`: Runs the 'build' script ONLY for the 'frontend' workspace.
  command = "npm install && npm run build -w frontend"

  # The location of your built frontend files (relative to the project root).
  publish = "frontend/dist"

  # The location of your backend serverless function (relative to the project root).
  functions = "backend"

# This rule makes your backend API available at the /api/ endpoint.
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/:splat"
  status = 200