[build]
  # Command to build the frontend
  command = "cd frontend && npm run build"

  # The final built frontend files
  publish = "frontend/dist"

  # The backend server code
  functions = "backend"

# Redirect rule to connect frontend to backend
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/:splat"
  status = 200